<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>Libs\</OutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SiegeEngine">
      <HintPath>C:\repos\Siege_Engine_Example_Projects\chess\Scripts\SiegeEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Foundation">
      <HintPath>C:\repos\Siege_Engine_Example_Projects\chess\Scripts\Foundation.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="obj/**/*.cs;Libs/**/*.cs;BuildOut/**/*.cs" />
  </ItemGroup>
</Project>
