<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>Libs\</OutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="SiegeEngine">
      <HintPath>SiegeEngine.dll</HintPath>
    </Reference>
    <Reference Include="Foundation">
      <HintPath>Foundation.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>
</Project>